### ISSUE TITLE
collect ve.direct data with python?

### ISSUE THREAD

**Issue by ekul00** [victronenergy/velib_python#3]
Hi @mpvader, others. I've recently got a Victron MPPT charge controller happily working here. It's doing an amazing job, and I'd like to collect performance data from it - to do things like run comparison analysis against weather data. Python would be ideal. Do you know of any plans to develop a ve.direct data collector (or something along these lines) whether or not as part of velib_python? Cheers!

**Comment by andriusst** [comment]
Just to say hi and that I also purchased MPPT 75/15 yesterday. I am also interested in ability to output data and potentially store it somewhere for later analysis. I will be watching this discussion with interest.

**Comment by andriusst** [comment]
@mpvader 
Hi, would you be able to share some reference about the hex protocol please? I have built a simple program on AutoIT to read and parse text and lay it down on GUI in a bit more friendly format. I am keen to find out what other stats or data can be pulled via the hex protocol. Thanks.

**Comment by mpvader** [comment]
@andriusst Hi! for some reason I never got a message of your request. I hope you got that file by now? If not, please send me an email at mvader@victronenergy.com, and I'll send you the VE.Direct hex documentation

**Comment by mpvader** [comment]
@all, fyi: see this page http://www.victronenergy.com/live/open_source:start

**Comment by bazsodombiandras** [comment]
Hello Guys!

I recently became the owner of a Victron Energy BlueSolar MPPT 100/15 charge controller and I realized that it is possible to connect it to a Raspberry Pi through the VE.Direct pins. I did find some code on the Internet that communicates with Victron products, but mostly BMVs, not charge controllers. Is there any existing C/C++ code or Pyhton code that you know of which can query the data from the BlueSolar MPPT 100/15 charge controller? I'm mainly interested in voltage, current, power and energy measurements at the battery connection, at the PV panel connection and at the load connection, but any code would be useful, I could modify it to my needs based on the Ve.Direct communication white paper.The ultimate purpose is to feed this data into awesome graphing tools like Cacti or home automation software like Domoticz, to make it available for myself over the web in form of nice graphs.

Thank you!

**Comment by mpvader** [comment]
@bazsodombiandras all that I know of is listed here: http://www.victronenergy.com/live/open_source:start

**Comment by bazsodombiandras** [comment]
Thank you, mpvader! I did check that out already. It's a start, but not quite what I was hoping for. Anyway, if I figure it out and write some useful code, I will make it available for everybody and let you know here.

**Comment by bazsodombiandras** [comment]
Guys, I apologize if this is not the right place to ask this question, but like I wrote, I'm trying to connect my BlueSolar charger to a Raspberry Pi through the VE.Direct port and I can't find any information whatsoever about how to make the physical connection.

VE.Direct has 4 pins:
1=Ground
2=TX
3=RX
4=Positive

As far as I understand things, BlueSolar TX should be connected to Raspberry Pi RX and BlueSolar RX to Raspberry Pi TX.
But should the two ground pins also be connected to each other (BlueSolar to Pi)? And more importantly, should the Positive pins also be connected to each other? If yes, which power pin of the Pi should be connected to the BlueSolar poisitive pin, the 5V or the 3.3V pin? What logic level does the BlueSolar use? 5V, 3.3V, maybe some other value?

Thank you!

**Comment by karioja** [comment]
BlueSolar uses 3.3V logic levels. Do not connect the 5V pin. At minimum you'll only need the GND pin and RX pin for receiving data from the controller.

**Comment by bazsodombiandras** [comment]
Thank you, karioja! I'll give it a try with RX and GND connection.

**Comment by bazsodombiandras** [comment]
I tried the following connection:
Pi GND to BlueSolar Pin 1 (GND)
Pi RX to BlueSolar Pin 2 (I suspect that this is the TX, but I'm not sure)

It does not seem to work unfortunately. Nothing is received by the Pi. I'm wondering about the following:
1. Is BlueSolar's pin 2 is indeed TX (the drawing is a bit ambiguous in the VE.Direct protocol whitepaper document)?
2. Is the BLueSolar transmitting every 1 second by default after turned on or the transmission has to be started somehow?
3. Is the BLueSolar transmitting when only connected to the Battery (green LED on), but not to the PV panels?
4. Is it enough to connect Pi RX to BlueSolar TX and GND to GND? Don't I need to also connect Pi TX to BlueSolar RX? If yes, that's a problem because it seems that Victron Energy has chosen a 4-pin connector with very tight pinout. There's not enough space in the 4 pin connector to connect 4 standard jumper wires. I can a\barely connect two of them. How did you guys achieve the physical connection? Using a VE.Direct cable? Unfortunately I don't own one of those...

**Comment by jhofstee** [comment]
Hi, which OS are you running on the Pi's?

**Comment by bazsodombiandras** [comment]
Raspbian.
This is how I open the serial communication in python:
ser = serial.Serial('/dev/ttyAMA0', baudrate=19200, timeout=1.5) 
The communication opens fine, but it also opens fine if the BlueSolar is not connected to the Pi. Nothing is received though. My guess is that there's a problem with the physical connection.

**Comment by andriusst** [comment]
The controller starts sending data as soon it is powered up. It is
recommended to never run off the solar alone. Attach battery first, only
then solar panels (if you need to).

It is sufficient gnd and tx pin connected on a controller side. I remember
I could not get it to work initially too and I think I ended up swapping rx
and tx pins on the solar controller end.

In regards to physical connection I also had similar issue. Could not find
the connector with the same spacing of pins. So I found some cable with
even smaller connector, removed the metal female pins and connected them
individually to the pins on the solar controller. It is a good idea to
enclose each female pin in heat shrink tubing beforehand to prevent
accidental shorting.

**Comment by bazsodombiandras** [comment]
Thank you, andriusst! I will try to swap the TX and RX on the BlueSolar side, perhaps that solves it. At least now I have confirmation that indeed only GND+TX works and that indeed this can be doen without a VE.Direct cable. It will be hard to find some small enough pins to attach to the BlueSolar, though. I'm wondering if that 4-pin connector on the BlueSolar is some kind of standard connector that you can find on other devices too and for which you can buy a female pair. I mean if it has a name and it's used in other devices too, perhaps I can buy such a connector (the female part), just like it's possible to buy an USB connector, a SATA connector etc.

**Comment by andriusst** [comment]
I know what you mean and I looked but could not find. The pins I used are
from USB FTDI flash stick cable white connector.

**Comment by bazsodombiandras** [comment]
I managed to find some really small female pin connectors, soldered some nice jumper cables onto them and connected those small pins to the VE.Direct port of the BlueSolar. At first I used pin 1 (GND) and 2 (which should be TX according to the VE.Direct whitepaper). Didn't work. So I used the BlueSolar's pin 3 instead (from left to right) and now it seems to work. Well, at least the Pi receives some data. It doesn't look at all like the data which is described in the VE.Direct whitepaper, though. It's just some binary stuff. Shouldn't the BLueSolar be in text mode? I've got firmware v1.15 installed on it.

**Comment by bazsodombiandras** [comment]
Used wrong baud rate (9600 instead of 19200). Corrected to 19200 and now it works beautifully! Thank you for your help and for those who might attempt doing the same, remember to use pins 1 (GND) and 3 from the BlueSolar charge controller and connect them to Raspberry Pi GND and RX.

**Comment by bazsodombiandras** [comment]
Now I have just one wish left: That the fields H17 and H18 (charged and discharged energy) be made available also for the BlueSolar charge controllers, not only for the BMVs :)

**Comment by jhofstee** [comment]
I put some notes here, http://www.victronenergy.com/live/open_source:ccgx:raspbian_deb, about things we use but then for a rpi (well only ve-direct is included at the moment, since it is just a test for now). I plan to add a simple example to use it in python.

**Comment by NickHibma** [comment]
Don't want to stir up an old conversation, but if I am reading this correctly then:

A) The VE.Direct port speaks 8N1 at 19200 at CMOS level (3.3V). Given that I can find a connector that fits the port, I could simply wire it to for example a CMOS level serial port on my PC Engines board?

B) The USB cable just provides a serial port. What driver does it use on the Linux side? FTDI? (I ask because I use FreeBSD, so need to know whether there is support)

Thanks in advance for any help!

**Comment by NickHibma** [comment]
Well, B) was just answered: Downloading the windows driver package shows that it is signed by FTDI, and provides the FTDI CDM drivers... Still would be interested whether I can skip the (expensive) cable in favour of a few wires.

**Comment by mpvader** [comment]
@NickHibma perhaps, yes. But don't forget isolation. See our VE.Direct Tezt protocol document on the whitepapers section on our website. And there is also a FAQ somewhere.

We always use isolation. If you don't, it might work, but you are on your own: no warranty if this will work, and also not on the bmv it this breaks the comm. port.

**Comment by isingthr4iam** [comment]
> I know what you mean and I looked but could not find. The pins I used are
> from USB FTDI flash stick cable white connector.
> On 24 Apr 2015 5:41 am, "bazsodombiandras" [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > Thank you, andriusst! I will try to swap the TX and RX on the BlueSolar
> > side, perhaps that solves it. At least now I have confirmation that indeed
> > only GND+TX works and that indeed this can be doen without a VE.Direct
> > cable. It will be hard to find some small enough pins to attach to the
> > BlueSolar, though. I'm wondering if that 4-pin connector on the BlueSolar
> > is some kind of standard connector that you can find on other devices too
> > and for which you can buy a female pair. I mean if it has a name and it's
> > used in other devices too, perhaps I can buy such a connector (the female
> > part), just like it's possible to buy an USB connector, a SATA connector
> > etc.
> > —
> > Reply to this email directly or view it on GitHub
> > [#3 (comment)](https://github.com/victronenergy/velib_python/issues/3#issuecomment-95799206)
> > .

By the way, that type of socket is called a JST connector. you can find literally hundreds of them on Amazon!  :-)
